version: '3.8'

services:
  app:
    container_name: 'fwd-backend'
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
    environment:
      PORT: ${PORT}
      POSTGRES_HOST: postgres_db
      REDIS_HOST: redis
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres_db
      - redis
    networks:
      myapp_net:

  postgres_db:
    image: postgres:17-alpine
    container_name: 'fwd-postgresql'
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASS}
      POSTGRES_DB: ${POSTGRE_DB}
      TZ: 'Asia/Manila'
    ports:
      - ${POSTGRE_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      myapp_net:

  redis:
    image: redis:8-alpine
    container_name: fwd-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      myapp_net:

volumes:
  postgres_data:
  redis_data:

networks:
  myapp_net:
